services:
  netzmacht.contao_cache_control.dca.page:
    class: Netzmacht\Contao\CacheControl\Dca\PageDca
    arguments:

  netzmacht.contao_cache_control.listener.add_page_tags:
    class: Netzmacht\Contao\CacheControl\Listener\AddPageTagsListener
    arguments:
